- hosts: all
  name: Deploy knitnet operator
  timeout: 200
  tasks:
  - name: Copy deploy knitnet script to remote node
    ansible.builtin.copy:
      src: scripts/deploy-knitnet.sh
      dest: /root/deploy-knitnet.sh
      mode: '0755'

  - name: Deploy knitnet operator
    ansible.builtin.shell:
      PROXY_SERVER={{PROXY_SERVER | default()}}
      PROXY_PORT={{PROXY_PORT | default()}}
      /root/deploy-knitnet.sh > /root/deploy-knitnet.log
