- hosts: broker
  gather_facts: False
  name: Deploy broker
  remote_user: root
  timeout: 100
  tasks:
  - name: Copy deploy broker script to remote node
    ansible.builtin.copy:
      src: scripts/deploy-broker.sh
      dest: /root/deploy-broker.sh
      mode: '0755'

  - name: Deploy broker
    ansible.builtin.shell: /root/deploy-broker.sh > deploy-broker.log

  - name: Save submariner-broker-info configmap to file
    ansible.builtin.shell: kubectl -n knitnet-operator-system get cm submariner-broker-info -oyaml > /root/submariner-broker-info.yaml
    retries: 10
    delay: 10
    register: result
    until: result.rc == 0

  - name: Copy submariner-broker-info configmap file to local
    ansible.builtin.fetch:
      src: /root/submariner-broker-info.yaml
      dest: submariner-broker-info.yaml
      flat: yes

- hosts: managed
  name: Copy submariner-broker-info configmap to managed cluster
  gather_facts: False
  remote_user: root
  tasks:
  - name: Copy submariner-broker-info configmap file to cluster
    ansible.builtin.copy:
      src: submariner-broker-info.yaml
      dest: /root/submariner-broker-info.yaml
      force: yes

  - name: Create submariner-broker-info configmap in cluster
    ansible.builtin.shell: |
      kubectl delete -f /root/submariner-broker-info.yaml
      kubectl apply -f /root/submariner-broker-info.yaml
