- hosts: all
  name: Join managed cluster to broker
  timeout: 100
  tasks:
  - name: Copy join broker script to remote node
    ansible.builtin.copy:
      src: scripts/join-broker.sh
      dest: /root/join-broker.sh
      mode: '0755'

  - name: Join to broker
    ansible.builtin.shell: /root/join-broker.sh {{ cluster_name }} > /root/join-broker.log
