- hosts: all
  name: Ensure managed cluster join to broker
  timeout: 200
  tasks:
  - name: Copy join script to remote node
    ansible.builtin.copy:
      src: scripts/join-broker.sh
      dest: /root/join-broker.sh
      mode: '0755'

  - name: Join cluster to broker
    ansible.builtin.shell: /root/join-broker.sh {{ cluster_name }} > /root/join-broker.log
